name: Node js test

on:
  push:
    branches: [master]

jobs:
  buildtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2.3.1
      - uses: actions/setup-node@2.1.1
        with:
          node-version: 13
      - run: npm ci
      - run: npm run build
      - run: npm test
